Revert "ci: move linting into flake"
https://github.com/ascandella/dotfiles/actions/runs/8362682116/job/22893853547

```
error: unable to execute '/nix/store/xwag02f294mv56fvw240wgrznadkbb73-lint/bin/lint': Exec format error
```

This reverts commit 9348e1a18ff452524a1d4f455de5d5d082144076.